/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

//import com.mysql.cj.x.protobuf.MysqlxDatatypes.Scalar.String;

import com.toedter.calendar.JDateChooser;
import crud.crudsuratkeluar;
import crud.crudsuratmasuk;
import database.koneksi;
import entitas.ensuratkeluar;
import entitas.ensuratmasuk;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static view.beranda.show;
/**
 *
 * @author ASUS
 */

public class surat extends javax.swing.JFrame {
    koneksi conn;
    Connection kon;
    crudsuratmasuk cr = new crudsuratmasuk();
    ensuratmasuk data = new ensuratmasuk();
    crudsuratkeluar crk = new crudsuratkeluar();
    ensuratkeluar dk = new ensuratkeluar();
    String nm,user,passw,sts;
    private String status;

    /**
     * Creates new form suratmasuk
     */
    Image img = null;
    ImageIcon icon = null;
    boolean editgbr = false;
    boolean editgk = false;
    
    InputStream is = null;
    InputStream isk = null;
    public surat() {
        initComponents();
        tabel();
        conn = new koneksi();
        kon =  conn.buatKoneksi();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    private void tabel(){
        tabelmasuk.setModel(cr.tampil());
        tabelkeluar.setModel(crk.tampil());

    }  
     public void setData(String n,String usr,String ps,String st){
        show.setText(n);
        nm = n;
        user=usr;
        passw = ps;
        sts=st; 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dari = new javax.swing.JTextField();
        tgl = new com.toedter.calendar.JDateChooser();
        no = new javax.swing.JTextField();
        ket = new javax.swing.JTextField();
        isi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lam = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelmasuk = new javax.swing.JTable();
        edit = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        cari = new javax.swing.JButton();
        car = new javax.swing.JTextField();
        pil = new javax.swing.JButton();
        gambar = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tgl1 = new com.toedter.calendar.JDateChooser();
        no1 = new javax.swing.JTextField();
        tujuan = new javax.swing.JTextField();
        isi1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lam1 = new javax.swing.JTextField();
        tambahk = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelkeluar = new javax.swing.JTable();
        editk = new javax.swing.JButton();
        resetk = new javax.swing.JButton();
        hapusk = new javax.swing.JButton();
        carik = new javax.swing.JButton();
        carikeluar = new javax.swing.JTextField();
        pilih = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        gbrk = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        surat = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1380, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA SURAT MASUK");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setText("Keterangan");

        dari.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        dari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dariKeyPressed(evt);
            }
        });

        tgl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        tgl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tglKeyPressed(evt);
            }
        });

        no.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                noKeyPressed(evt);
            }
        });

        ket.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        ket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ketKeyPressed(evt);
            }
        });

        isi.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        isi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                isiKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setText("Nomor Surat");

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setText("Tanggal Terima");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setText("Terima Dari");

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setText("Lampiran (halaman)");

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setText("Isi/Prihal");

        lam.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lamKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lamKeyTyped(evt);
            }
        });

        tambah.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        tabelmasuk.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        tabelmasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelmasukMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelmasuk);

        edit.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/undo.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        hapus.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        cari.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        car.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N

        pil.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        pil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pilih.png"))); // NOI18N
        pil.setText("Pilih Foto Surat");
        pil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilMouseClicked(evt);
            }
        });
        pil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilActionPerformed(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mail (3).png"))); // NOI18N
        jLabel20.setText("jLabel20");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mail (3).png"))); // NOI18N
        jLabel21.setText("jLabel20");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pil)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lam, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(isi, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dari, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tgl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(no, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ket))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(car, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(cari)
                                .addGap(23, 23, 23))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 244, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(387, 387, 387))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cari)
                            .addComponent(car, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(tambah)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(dari, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(edit))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(isi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(reset))))
                                    .addComponent(gambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(hapus))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ket, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pil)
                        .addGap(239, 239, 239))))
        );

        jTabbedPane1.addTab("Surat Masuk", jPanel1);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel9.setText("DATA SURAT KELUAR");

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel10.setText("Tujuan");

        tgl1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        tgl1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tgl1KeyPressed(evt);
            }
        });

        no1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no1ActionPerformed(evt);
            }
        });
        no1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                no1KeyPressed(evt);
            }
        });

        tujuan.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        tujuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tujuanKeyPressed(evt);
            }
        });

        isi1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        isi1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                isi1KeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel11.setText("Nomor Surat");

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel13.setText("Tanggal Kirim");

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel14.setText("Lampiran (halaman)");

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel17.setText("Isi/Prihal");

        lam1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lam1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lam1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lam1KeyTyped(evt);
            }
        });

        tambahk.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        tambahk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        tambahk.setText("Tambah");
        tambahk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahkActionPerformed(evt);
            }
        });

        tabelkeluar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        tabelkeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelkeluarMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelkeluar);

        editk.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        editk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        editk.setText("Edit");
        editk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editkActionPerformed(evt);
            }
        });

        resetk.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        resetk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/undo.png"))); // NOI18N
        resetk.setText("Reset");
        resetk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetkActionPerformed(evt);
            }
        });

        hapusk.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        hapusk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        hapusk.setText("Hapus");
        hapusk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapuskActionPerformed(evt);
            }
        });

        carik.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        carik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        carik.setText("Cari");
        carik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carikActionPerformed(evt);
            }
        });

        carikeluar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        carikeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carikeluarActionPerformed(evt);
            }
        });

        pilih.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        pilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pilih.png"))); // NOI18N
        pilih.setText("Pilih Gambar Surat");
        pilih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilihMouseClicked(evt);
            }
        });
        pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihActionPerformed(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mail.png"))); // NOI18N
        jLabel18.setText("jLabel18");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mail.png"))); // NOI18N
        jLabel19.setText("jLabel18");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(565, 565, 565)
                        .addComponent(carikeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(carik)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel9)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(357, 357, 357))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(pilih)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lam1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(no1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isi1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hapusk, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tambahk)
                                    .addComponent(editk, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resetk, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addComponent(gbrk, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(no1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tgl1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isi1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lam1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(tambahk)
                        .addGap(29, 29, 29)
                        .addComponent(editk)
                        .addGap(47, 47, 47)
                        .addComponent(resetk)
                        .addGap(47, 47, 47)
                        .addComponent(hapusk))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gbrk, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(carikeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(carik))
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(44, 44, 44)
                .addComponent(pilih)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Surat Keluar", jPanel6);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(220, 50, 1310, 790);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kecil.jpg"))); // NOI18N
        jLabel12.setText("jLabel1");

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Welcome");

        show.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home-page.png"))); // NOI18N
        home.setText("jLabel8");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        surat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/letter.png"))); // NOI18N
        surat.setText("jLabel8");
        surat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suratMouseClicked(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reg.png"))); // NOI18N
        jLabel23.setText("jLabel4");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        jLabel24.setText("jLabel5");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(67, 67, 67))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surat, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(10, 10, 10)
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(surat)
                .addGap(67, 67, 67)
                .addComponent(jLabel23)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, -6, 220, 850);

        jPanel3.setBackground(javax.swing.UIManager.getDefaults().getColor("nb.startpage.rss.header.color"));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        jLabel16.setText("jLabel6");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(1278, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 105, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(220, 0, 1310, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void pilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilActionPerformed

    private void pilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilMouseClicked
        // TODO add your handling code here:
        JFileChooser open = new JFileChooser("D:/Pelatihan JAVA/Project/src/image");
        File f = new File("");
        int r = open.showOpenDialog(null);
        if(r == JFileChooser.APPROVE_OPTION){
            f = open.getSelectedFile();

            try {
                is = new FileInputStream(new File(f.getAbsoluteFile().toString()));
                data.setGbr(is);

            } catch (FileNotFoundException ex) {
                Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_pilMouseClicked

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        String by = car.getText();
        tabelmasuk.setModel(cr.cari(by));
    }//GEN-LAST:event_cariActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        data.setNo(tabelmasuk.getValueAt(tabelmasuk.getSelectedRow(), 0).toString());
        try {
            cr.delete(data);
            no.setText("");
            tgl.setDate(null);
            dari.setText("");
            isi.setText("");
            lam.setText("");
            ket.setText("");
            tabel();
            JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");

        } catch (SQLException ex) {
            Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_hapusActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        no.setText("");
        tgl.setDate(null);
        dari.setText("");
        isi.setText("");
        lam.setText("");
        ket.setText("");
        gambar.setIcon(null);
    }//GEN-LAST:event_resetActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        editgk = true;
        
        String tanggal = "YYYY-MM-dd";
        SimpleDateFormat dateFormat = new SimpleDateFormat(tanggal);
        data.setNo(no.getText());
        if(no.getText().isEmpty() || dari.getText().isEmpty() || isi.getText().isEmpty() || lam.getText().isEmpty() || ket.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Data Harus Lengkap");
        }else{
            if(is == null){
                int index = tabelmasuk.getSelectedRow();
                data.setNo(tabelmasuk.getValueAt(index, 0).toString());
                try {
                    is = new ByteArrayInputStream((byte[])cr.frameLogoModel(data));
                    data.setGbr(is);
                    cr.edit(data);
                } catch (SQLException ex) {
                    Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            data.setTgl(String.valueOf(dateFormat.format(tgl.getDate())));
            data.setDari(dari.getText());
            data.setIsi(isi.getText());
            data.setLam(lam.getText());
            data.setKet(ket.getText());
            try {
                if(cr.edit(data)==0){
                    JOptionPane.showMessageDialog(null,"Data Berhasil Diedit");
                    tabel();
                }else{
                    JOptionPane.showMessageDialog(null,"Data Gagal Diedit");
                }
            } catch (SQLException ex) {
                Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_editActionPerformed

    private void tabelmasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelmasukMouseClicked
        // TODO add your handling code here:
        int index = tabelmasuk.getSelectedRow();
        data.setNo(tabelmasuk.getValueAt(index, 0).toString());
        try {
            byte[] p = (byte[])cr.frameLogoModel(data);
            System.out.println(p);
            img = Toolkit.getDefaultToolkit().createImage(p);
            icon = new ImageIcon(img);
            gambar.setIcon(icon);

        } catch (SQLException ex) {
            Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
        }
        no.setText(tabelmasuk.getValueAt(index, 0).toString());
        String t = tabelmasuk.getValueAt(index, 1).toString();
        java.util.Date tanggal;
        try {
            tanggal = new SimpleDateFormat("YYYY-MM-dd").parse(t);
            tgl.setDate(tanggal);
        } catch (ParseException ex) {
            Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        dari.setText(tabelmasuk.getValueAt(index, 2).toString());
        isi.setText(tabelmasuk.getValueAt(index, 3).toString());
        lam.setText(tabelmasuk.getValueAt(index, 4).toString());
        ket.setText(tabelmasuk.getValueAt(index, 5).toString());
    }//GEN-LAST:event_tabelmasukMouseClicked

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        String tanggal = "YYYY-MM-dd";
        SimpleDateFormat dateFormat = new SimpleDateFormat(tanggal);
        data.setNo(no.getText());
        if(cr.cek(data)==1){
            JOptionPane.showMessageDialog(null,"Data Sudah Ada");
        }else{
            if(no.getText().isEmpty() || dari.getText().isEmpty() || isi.getText().isEmpty() || lam.getText().isEmpty() || ket.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Data Harus Lengkap");
            }else{
                data.setTgl(String.valueOf(dateFormat.format(tgl.getDate())));
                data.setDari(dari.getText());
                data.setIsi(isi.getText());
                data.setLam(lam.getText());
                data.setKet(ket.getText());
                try {
                    if(cr.tambah(data)==0){
                        JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
                        tabel();
                    }else{
                        JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void lamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lamKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            ket.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            isi.requestFocus();
        }
    }//GEN-LAST:event_lamKeyPressed

    private void isiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            lam.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            dari.requestFocus();
        }
    }//GEN-LAST:event_isiKeyPressed

    private void noKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tgl.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            ket.requestFocus();
        }
        
    }//GEN-LAST:event_noKeyPressed

    private void tglKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tglKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            dari.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            no.requestFocus();
        }
    }//GEN-LAST:event_tglKeyPressed

    private void dariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dariKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            isi.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            tgl.requestFocus();
        }
    }//GEN-LAST:event_dariKeyPressed

    private void tambahkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahkActionPerformed
        // TODO add your handling code here:
        String tanggal = "YYYY-MM-dd";
        SimpleDateFormat dateFormat = new SimpleDateFormat(tanggal);
        dk.setNo(no1.getText());
        if(crk.cek(dk)==1){
            JOptionPane.showMessageDialog(null,"Data Sudah Ada");
        }else{
            if(no1.getText().isEmpty() || isi1.getText().isEmpty() || lam1.getText().isEmpty() || tujuan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Data Harus Lengkap");
            }else{
                dk.setTgl(String.valueOf(dateFormat.format(tgl1.getDate())));
                dk.setIsi(isi1.getText());
                dk.setTujuan(tujuan.getText());
                dk.setLam(lam1.getText());
                try {
                    if(crk.tambah(dk)==0){
                        JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
                        tabel();
                    }else{
                        JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
                } 
            }
        }
    }//GEN-LAST:event_tambahkActionPerformed

    private void tabelkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelkeluarMouseClicked
        // TODO add your handling code here:
        int index = tabelkeluar.getSelectedRow();
        dk.setNo(tabelkeluar.getValueAt(index, 0).toString());
        try {
            byte[] p = (byte[])crk.frameLogoModel(dk);
            System.out.println(p);
            img = Toolkit.getDefaultToolkit().createImage(p);
            icon = new ImageIcon(img);
            gbrk.setIcon(icon);

        } catch (SQLException ex) {
            Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
        }
        no1.setText(tabelkeluar.getValueAt(index, 0).toString()); 
        String t = tabelkeluar.getValueAt(index, 1).toString();
        java.util.Date tanggal;
        try {
            tanggal = new SimpleDateFormat("YYYY-MM-dd").parse(t);
            tgl1.setDate(tanggal);
        } catch (ParseException ex) {
            Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
        }
        isi1.setText(tabelkeluar.getValueAt(index, 2).toString());
        tujuan.setText(tabelkeluar.getValueAt(index, 3).toString());
        lam1.setText(tabelkeluar.getValueAt(index, 4).toString());
    
    }//GEN-LAST:event_tabelkeluarMouseClicked

    private void editkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editkActionPerformed
        // TODO add your handling code here:
        editgk = true;
        String tanggal = "YYYY-MM-dd";
        SimpleDateFormat dateFormat = new SimpleDateFormat(tanggal);
        dk.setNo(no1.getText());
            if(no1.getText().isEmpty() || isi1.getText().isEmpty() || lam1.getText().isEmpty() || tujuan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Data Harus Lengkap");
            }else{
                if(isk == null){
                    int index = tabelkeluar.getSelectedRow();
                    dk.setNo((tabelkeluar.getValueAt(index, 0).toString()));
                    
                    try {
                        isk = new ByteArrayInputStream((byte[])crk.frameLogoModel(dk));
                        dk.setGbr(isk);
                        crk.edit(dk);
                    } catch (SQLException ex) {
                        Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                dk.setTgl(String.valueOf(dateFormat.format(tgl1.getDate())));
                dk.setIsi(isi1.getText());
                dk.setTujuan(tujuan.getText());
                dk.setLam(lam1.getText());
                try {
                    if(crk.edit(dk)==0){
                        JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
                        tabel();
                    }else{
                        
                        JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
                } 
            }
        
    }//GEN-LAST:event_editkActionPerformed

    private void resetkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetkActionPerformed
        // TODO add your handling code here:
        no1.setText("");
        tgl1.setDate(null);
        isi1.setText("");
        tujuan.setText("");
        lam1.setText("");
    }//GEN-LAST:event_resetkActionPerformed

    private void hapuskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapuskActionPerformed
        // TODO add your handling code here:
        dk.setNo(tabelkeluar.getValueAt(tabelkeluar.getSelectedRow(), 0).toString());
        try {
            crk.delete(dk);
            no1.setText("");
            tgl1.setDate(null);
            isi1.setText("");
            tujuan.setText("");
            lam1.setText("");
            gambar.setIcon(null);
            tabel();
            JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");
        
        } catch (SQLException ex) {
            Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }//GEN-LAST:event_hapuskActionPerformed

    private void carikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carikActionPerformed
        // TODO add your handling code here:
        String by = carikeluar.getText();
        tabelkeluar.setModel(crk.cari(by));
    }//GEN-LAST:event_carikActionPerformed

    private void carikeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carikeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carikeluarActionPerformed

    private void pilihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilihMouseClicked
      JFileChooser open = new JFileChooser("D:/Pelatihan JAVA/Project/src/image");
        File f = new File("");
        int r = open.showOpenDialog(null);
        if(r == JFileChooser.APPROVE_OPTION){
            f = open.getSelectedFile();

            try {
                isk = new FileInputStream(new File(f.getAbsoluteFile().toString()));
                dk.setGbr(isk);

            } catch (FileNotFoundException ex) {
                Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_pilihMouseClicked

    private void pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihActionPerformed
        // TODO add your handling code here:      
                
    }//GEN-LAST:event_pilihActionPerformed

    private void no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no1ActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        this.dispose();
        beranda b = new beranda();
        b.setVisible(true);
        b.setData(nm,user,passw,sts);
    }//GEN-LAST:event_homeMouseClicked

    private void suratMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suratMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Anda Sudah berada di menu Surat");

    }//GEN-LAST:event_suratMouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        if(sts.equals("Direksi")){
            this.dispose();
            pengguna p = new pengguna();
            p.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Hanya Direksi yang dapat membuka menu ini");
        }
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void no1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tgl1.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            lam1.requestFocus();
        }
    }//GEN-LAST:event_no1KeyPressed

    private void tgl1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgl1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            isi1.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            no1.requestFocus();
        }
    }//GEN-LAST:event_tgl1KeyPressed

    private void isi1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isi1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tujuan.requestFocus();
        }
        
    }//GEN-LAST:event_isi1KeyPressed

    private void tujuanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tujuanKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            lam1.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            isi1.requestFocus();
        }
    }//GEN-LAST:event_tujuanKeyPressed

    private void ketKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ketKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            lam.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            no.requestFocus();
        }
    }//GEN-LAST:event_ketKeyPressed

    private void lam1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lam1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            no1.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            tujuan.requestFocus();
        }
    }//GEN-LAST:event_lam1KeyPressed

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
        akun a = new akun();
        a.set(nm, user, passw, sts);
        a.setVisible(true);
    }//GEN-LAST:event_jLabel24MouseClicked

    private void lamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lamKeyTyped
        // TODO add your handling code here:
        if( ! (Character.isDigit(evt.getKeyChar()) || evt.getKeyChar() == KeyEvent.VK_DELETE || evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) ){
            evt.consume();//menghilangkan inputan
            JOptionPane.showMessageDialog(this,"Inputan Hanya Boleh Angka","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_lamKeyTyped

    private void lam1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lam1KeyTyped
        // TODO add your handling code here:
        if( ! (Character.isDigit(evt.getKeyChar()) || evt.getKeyChar() == KeyEvent.VK_DELETE || evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) ){
            evt.consume();//menghilangkan inputan
            JOptionPane.showMessageDialog(this,"Inputan Hanya Boleh Angka","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_lam1KeyTyped
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new surat().setVisible(true);
//                show.setText();
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField car;
    private javax.swing.JButton cari;
    private javax.swing.JButton carik;
    private javax.swing.JTextField carikeluar;
    private javax.swing.JTextField dari;
    private javax.swing.JButton edit;
    private javax.swing.JButton editk;
    private javax.swing.JLabel gambar;
    private javax.swing.JLabel gbrk;
    private javax.swing.JButton hapus;
    private javax.swing.JButton hapusk;
    private javax.swing.JLabel home;
    private javax.swing.JTextField isi;
    private javax.swing.JTextField isi1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public static final javax.swing.JLabel jLabel15 = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField ket;
    private javax.swing.JTextField lam;
    private javax.swing.JTextField lam1;
    private javax.swing.JTextField no;
    private javax.swing.JTextField no1;
    private javax.swing.JButton pil;
    private javax.swing.JButton pilih;
    private javax.swing.JButton reset;
    private javax.swing.JButton resetk;
    public static final javax.swing.JLabel show = new javax.swing.JLabel();
    private javax.swing.JLabel surat;
    private javax.swing.JTable tabelkeluar;
    private javax.swing.JTable tabelmasuk;
    private javax.swing.JButton tambah;
    private javax.swing.JButton tambahk;
    private com.toedter.calendar.JDateChooser tgl;
    private com.toedter.calendar.JDateChooser tgl1;
    private javax.swing.JTextField tujuan;
    // End of variables declaration//GEN-END:variables

    private String frameLogoModel(ensuratmasuk data) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

  
}
